// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGywKhIwwRhQc20jkRHZCLZtqOahtYOX0',
    appId: '1:17649715144:web:69069b1ae47b46be7962fd',
    messagingSenderId: '17649715144',
    projectId: 'revmedapp-d6a4a',
    authDomain: 'revmedapp-d6a4a.firebaseapp.com',
    storageBucket: 'revmedapp-d6a4a.appspot.com',
    measurementId: 'G-CM78WFQ3SD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFH1PVEHYR9Pl296a4IOWcoK8XEanqu6s',
    appId: '1:17649715144:android:027bcec2a1a1f64b7962fd',
    messagingSenderId: '17649715144',
    projectId: 'revmedapp-d6a4a',
    storageBucket: 'revmedapp-d6a4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaRbKJBKM_ul01eiySuPzEfbm5IMlCj00',
    appId: '1:17649715144:ios:78800e01550755a77962fd',
    messagingSenderId: '17649715144',
    projectId: 'revmedapp-d6a4a',
    storageBucket: 'revmedapp-d6a4a.appspot.com',
    iosBundleId: 'com.example.revmed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaRbKJBKM_ul01eiySuPzEfbm5IMlCj00',
    appId: '1:17649715144:ios:78800e01550755a77962fd',
    messagingSenderId: '17649715144',
    projectId: 'revmedapp-d6a4a',
    storageBucket: 'revmedapp-d6a4a.appspot.com',
    iosBundleId: 'com.example.revmed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGywKhIwwRhQc20jkRHZCLZtqOahtYOX0',
    appId: '1:17649715144:web:5a5cb934584988b67962fd',
    messagingSenderId: '17649715144',
    projectId: 'revmedapp-d6a4a',
    authDomain: 'revmedapp-d6a4a.firebaseapp.com',
    storageBucket: 'revmedapp-d6a4a.appspot.com',
    measurementId: 'G-9Y4FQ5H0NK',
  );

}